Config = {}

------------------------------------------------------------------------------------------------------
-- ZOMBIES
------------------------------------------------------------------------------------------------------

Config.ZombieTypes = {

    normal = {
        models = {
            'u_m_y_zombie_01',
        },
        damage = 10,
        speed = 2.0, -- You can use this to change their speed when chasing
        ragdollChance = 10,
        clipsets = {"move_m@drunk@verydrunk"},
        sound = "explosive.ogg" -- Specific sound for this type
    },

    fast = {
        models = {
            'g_m_m_zombie_01', -- Need build 3258 for this ped
        },
        damage = 8,
        speed = 3,
        ragdollChance = 10,
        clipsets = {"move_m@drunk@verydrunk"},
        sound = "fast.ogg"
    },

    tank = {
        models = {
            'g_m_m_zombie_02', -- Need build 3258 for this ped
        },
        damage = 20,
        speed = 1.0,
        ragdollChance = 75,
        clipsets = {"move_m@drunk@verydrunk"},
        sound = "tanque.ogg"
    }

}

------------------------------------------------------------------------------------------------------
-- ZOMBIES | GENERAL SETTINGS
------------------------------------------------------------------------------------------------------

-- Zombie Blips
Config.ShowZombieBlips = true  -- Allow showing blips of nearby zombies
Config.ZombieBlipRadius = 80.0 -- Radius in which zombie blips will be shown
Config.ZombieBlip = {
    Sprite = 1,      -- Blip icon
    Colour = 1,      -- Color (1 = red)
    Scale = 0.7,     -- Blip size
    Name = "Zombie"  -- Name that appears on the map
}

-- General behavior
Config.SpawnRadius = 50.0
Config.ZombieAttackInterval = 1000
Config.DespawnTime = 15000
Config.MaxZombiesPerPlayer = 10
Config.SpawnInterval = 5000 -- Interval between spawn attempts (ms)
Config.ZombiesPerSpawn = 1 -- Zombies to spawn per normal cycle
Config.HordeSpawnThreshold = 0.3 -- Percentage of max (0.3 = 30%) to activate horde mode
Config.HordeSpawnMultiplier = 3 -- Zombie multiplier when in horde mode (3x)
Config.MaxSpawnAttempts = 5 -- Maximum spawn attempts per cycle (to avoid blocking)

-- Multiplayer optimization settings
Config.PlayerCacheUpdateInterval = 3000 -- How often to update player cache (ms) - lower = more accurate but more expensive
Config.MaxPlayerDetectionDistance = 150.0 -- Maximum distance to detect players (optimization - ignore players beyond this)
Config.PlayerCacheMaxDistance = 200.0 -- Maximum distance to cache players (optimization)

-- Vehicles
Config.ZombiesCanPullOut = false -- Enable or disable zombies being able to pull the player out of the vehicle
Config.PullOutChance = 50         -- Probability (in %) that a zombie will attempt to pull the player out of the vehicle
Config.VehicleDamageOnAttack = 25 -- Amount of damage done to the vehicle engine per attack

-- Vehicle interaction settings
Config.VehicleAttackDistance = 1.5  -- Distance at which the zombie damages the vehicle
Config.VehiclePullOutDistance = 3.0   -- Distance at which the zombie attempts to enter the vehicle
Config.PushForce = 2.0              -- Force with which the vehicle is pushed
Config.DistanceTarget = 5.0         -- Target distance for the zombie to approach the vehicle

-- Vision and search parameters
Config.DayVisionDistance = 80.0
Config.NightVisionDistance = 40.0
Config.SearchTime = 10000

-- Audio/detection
Config.HearingRadius = 250.0        -- Base hearing radius
Config.NoiseMemoryTime = 15000      -- Time in ms that the zombie remembers the last noise

-- Additional noise settings
Config.FootstepsNoiseRadius = 30.0   -- Noise generated by footsteps when running
Config.VehicleHighSpeedNoise = 100.0 -- Noise when driving fast
Config.VehicleSpeedThreshold = 15.0  -- m/s, above this is considered noisy
Config.ClaxonNoiseRadius = 80.0      -- Noise when honking the horn

Config.CollisionNoiseRadius = 120.0  -- Noise from strong collision
Config.CollisionSpeedDrop = 10.0     -- Speed difference (m/s) considered a strong collision

Config.AttackRadius = 500.0 -- Noise if the weapon is silenced

------------------------------------------------------------------------------------------------------
-- FRAMEWORK & LOOT SETTINGS
------------------------------------------------------------------------------------------------------
Config.Framework = 'QBCORE' -- 'ESX' or 'QBCORE'
Config.EnableZombieLoot = true -- Enable or disable the loot system

Config.LootKey = 38 -- E = 38 en GTA KeyMapping
Config.LootDistance = 4.0

Config.ZombieLootItems = {
    {item = 'bandage', min = 1, max = 3, chance = 50}, 
    {item = 'water', min = 1, max = 2, chance = 30},
    {item = 'bread', min = 1, max = 2, chance = 20}
}

------------------------------------------------------------------------------------------------------
-- SAFEZONES & REDZONES
------------------------------------------------------------------------------------------------------

Config.ShowRedZoneBlips = true   -- Show redzone blips
Config.RedZoneBlip = {
    Sprite = 310,
    Colour = 1,
    Scale = 1.0,
    Name = "Redzone"
}

Config.ShowSafeZoneBlips = true  -- Show safezone blips
Config.SafeZoneBlip = {
    Sprite = 305,
    Colour = 2,
    Scale = 1.0,
    Name = "Safezone"
}

-- Define RedZones (where zombies can spawn)
Config.RedZones = {
    {coords = vector3(-2050.8552, -574.9294, 4.7846), radius = 10000.0},
    --{coords = vector3(200.0, 200.0, 200.0), radius = 300.0}
}

-- Define SafeZones (where zombies despawn)
Config.SafeZones = {
    {coords = vector3(-2080.5789, -500.3755, 6.8020), radius = 50.0}, 
    --{coords = vector3(-350.0, -450.0, 33.0), radius = 150.0}
}